"""
Django settings for testPlatform project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import logging
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import common.exception_handler

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mgfngppkuhznosh)@3)ov%lc1=0f#1sd)w-v1@aubsr$uzep&0'

# SECURITY WARNING: don't run with debug turned on in production!
# MESSAGE_LOG = os.path.join(os.path.curdir, 'message.log')
LOG_DIR = os.path.join(os.path.curdir, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

DEBUG = True
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,  # 禁用已经存在的logger实例
    'formatters': {
        # 详细的日志格式
        'standard': {
            'format': '%(asctime)s,%(process)d,%(name)s,%(levelname)s,%(filename)s:%(lineno)d,%(message)s'
        },
        # 简单的日志格式
        'simple': {
            'format': '%(asctime)s | %(levelname)-8s | %(name)s %(filename)s:%(funcName)s:%(lineno)d - %(message)s'
        },
        # 定义一个特殊的日志格式
        'collect': {
            'format': '%(message)s'
        }
    },
    # 过滤器
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 默认的
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(LOG_DIR, "message.log"),
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 50M
            'backupCount': 5,  # 最多备份5个
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        # 专门用来记错误日志
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(LOG_DIR, "error.log"),  # 日志文件
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 50M
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        # 在终端打印
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],  # 只有在Django debug为True时才在屏幕打印日志
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 专门用来记录需要发送到邮件的日志
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            # 'filters': ['special'],
        },
        # 专门定义一个收集app：api_test的日志
        'api_test_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': os.path.join(LOG_DIR, "api_test.log"),
            'maxBytes': 1024 * 1024 * 50,  # 日志大小 50M
            'backupCount': 5,
            'formatter': 'simple',
            'encoding': "utf-8"
        },
        # 收集脚本日志
        'scprits_handler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, "script.log"),
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        }
    },
    'loggers': {
        # 默认的logger应用如下配置
        'django': {
            'handlers': ['default', 'error', 'console'] if DEBUG else ["default", 'error'],
            'level': 'DEBUG',
            'propagate': False,  # 是否向更高级别的logger传递
        },
        # 名为 'api_test'的logger 单独处理
        'api_test': {
            'handlers': ['api_test_handler', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # 名为 'scripts'的logger 单独处理
        'scripts': {
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False
        },
        # 'root' logger
        '': {
            'handlers': ['default', 'console'] if DEBUG else ["default"],
            'level': 'DEBUG',
            'propagate': False
        },
    }
}

ALLOWED_HOSTS = ["*"]

# AUTH_USER_MODEL = 'user.UserProfile'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django_filters',
    'rest_framework',
    'corsheaders',

    'apps.user_auth.apps.UserAuthConfig',
    'apps.api_test.apps.ApiTestConfig',
    'apps.bug_analysis.apps.BugAnalysisConfig',
    'apps.precise.apps.PreciseConfig',

    # 使用django-rest-auth自带登录注册api  -- 放弃
    # 'allauth',
    # 'allauth.account',
    # 'rest_auth.registration'
]
SITE_ID = 1  # django-rest-auth配置

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic',
        }
    },
    'USE_SESSION_AUTH': True
}

LOGIN_URL = 'rest_framework:login'
LOGOUT_URL = 'rest_framework:logout'

REST_FRAMEWORK = {
    #     'DEFAULT_PERMISSION_CLASSES': (
    #         'rest_framework.permissions.IsAuthenticated',
    #     ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    #     'DEFAULT_PAGINATION_CLASS': (
    #         'rest_framework.pagination.PageNumberPagination',
    #     ),
    'EXCEPTION_HANDLER': 'common.exception_handler.exception_handler',
    # 'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
    "DEFAULT_THROTTLE_RATES": {
        # key与定义的scope对应，value: 5表示次数 / m表示分钟  s秒  h小时  d天
        "api_update_history_add": "5/m",
    }
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "UiProject/dist/static"),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ORIGINS_ALLOW_ALL = True
ROOT_URLCONF = 'testPlatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'UiProject/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testPlatform.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 配置使用 服务器mysql
        'ENGINE': 'django.db.backends.mysql',  # 数据库产品
        'HOST': "localhost",  # 数据库ip  47.99.145.123 / localhost / 192.168.0.208
        'PORT': 3306,  # 数据库端口
        'USER': "root",  # 用户名
        'PASSWORD': "Abcd1234",  # 密码
        'NAME': "Apiplatform",  # 数据库名
    },
    'default2': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'default3': {
        # 配置使用 本地mysql
        'ENGINE': 'django.db.backends.mysql',  # 数据库产品
        'HOST': "localhost",  # 数据库ip  localhost
        'PORT': 3306,  # 数据库端口
        'USER': "root",  # 用户名
        'PASSWORD': "tangxiaoyu1.",  # 密码
        'NAME': "apiplatform",  # 数据库名
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'  # 'en-us'

TIME_ZONE = 'Asia/Shanghai'  # 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# 跨域忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    # '*',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://*.*.*.*:*'
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-token',
    'x-csrftoken',
    'x-requested-with',
    'Pragma'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
