# Generated by Django 3.2.5 on 2022-01-27 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='tester', max_length=10, verbose_name='角色')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='头像')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号码')),
                ('status', models.BooleanField(default=True, verbose_name='状态（1正常 0停用）')),
                ('description', models.CharField(blank=True, max_length=4096, null=True, verbose_name='描述')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='用户资料', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
            },
        ),
    ]
