# Generated by Django 3.2.6 on 2021-09-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFunction',
            fields=[
                ('module_function_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='功能id')),
                ('module_function_name', models.CharField(max_length=255, null=True, verbose_name='功能id')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块功能',
                'verbose_name_plural': '模块功能',
            },
        ),
        migrations.CreateModel(
            name='PrimaryModule',
            fields=[
                ('primary_module_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='一级模块id')),
                ('primary_module_name', models.CharField(max_length=255, null=True, verbose_name='一级模块名')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '一级模块',
                'verbose_name_plural': '一级模块',
            },
        ),
        migrations.CreateModel(
            name='SecondaryModule',
            fields=[
                ('secondary_module_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='二级模块id')),
                ('secondary_module_name', models.CharField(max_length=255, null=True, verbose_name='二级模块名')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('primary_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precise.primarymodule', verbose_name='一级模块id')),
            ],
            options={
                'verbose_name': '二级模块',
                'verbose_name_plural': '二级模块',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='系统id')),
                ('system_name', models.CharField(max_length=255, verbose_name='系统名')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统表',
                'verbose_name_plural': '系统表',
            },
        ),
        migrations.CreateModel(
            name='ThirdModule',
            fields=[
                ('third_module_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='三级模块id')),
                ('third_module_name', models.CharField(max_length=255, null=True, verbose_name='三级模块名')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('secondary_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precise.secondarymodule', verbose_name='二级模块id')),
            ],
            options={
                'verbose_name': '三级模块',
                'verbose_name_plural': '三级模块',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('case_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='用例id')),
                ('case_title', models.CharField(max_length=255, null=True, verbose_name='用例名')),
                ('precondition', models.CharField(max_length=255, null=True, verbose_name='前置条件')),
                ('operation_steps', models.CharField(max_length=1000, null=True, verbose_name='操作步骤')),
                ('expected_results', models.CharField(max_length=255, null=True, verbose_name='预期结果')),
                ('actual_results', models.CharField(max_length=255, null=True, verbose_name='实际结果')),
                ('executor', models.CharField(max_length=20, null=True, verbose_name='执行人')),
                ('execution_times', models.DateTimeField(null=True, verbose_name='执行时间')),
                ('number_of_runs', models.IntegerField(null=True, verbose_name='执行次数')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('direct_func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precise.modulefunction', verbose_name='用例所属功能')),
            ],
            options={
                'verbose_name': '功能关联',
                'verbose_name_plural': '功能关联',
            },
        ),
        migrations.AddField(
            model_name='primarymodule',
            name='system',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='precise.system', verbose_name='系统id'),
        ),
        migrations.AddField(
            model_name='modulefunction',
            name='third_modle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precise.thirdmodule', verbose_name='三级模块id'),
        ),
        migrations.CreateModel(
            name='FunctionalRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('update_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('direct_func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_func', to='precise.modulefunction', verbose_name='功能')),
                ('indirect_impact_func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirect_impact_func', to='precise.modulefunction', verbose_name='关联功能')),
            ],
            options={
                'verbose_name': '功能关联',
                'verbose_name_plural': '功能关联',
            },
        ),
    ]
